import "./globals.css";
import HeaderTop from "@/components/HeaderTop";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <HeaderTop />
        {children}
      </body>
    </html>
  );
}
