import Head from "next/head";
import { Header } from "../components/header.jsx";
import { SectionBanner } from "../components/section-banner.jsx";
import { SectionRequisitos } from "../components/section-requisitos.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <SectionBanner />
        <SectionRequisitos />
      </>
    </>
  );
}
